CREATE TABLE proxies
(
	id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
	host VARCHAR(250) NOT NULL, 
	port INTEGER NOT NULL, 
	user_name VARCHAR(250), 
	password VARCHAR(250), 
	secure BOOLEAN NOT NULL, 
	default_proxy BOOLEAN NOT NULL, 
	
	CONSTRAINT primary_key PRIMARY KEY (id)
)